/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw5.wkdgkdudd;
/**
 * app
 */
public class App {
    /**
     * getgreeting
     * @return
     */
    public String getGreeting() {
        return "Hello World!";
    }
/**
 * main
 * @param args
 */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
