/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.handong.csee.java.hw5;

/**
 * This is the app
 */

public class App {
    /**
     * app greeting
     * @return
     */
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * app main
     * @param args
     */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
