/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw5.h.zzn;
/**
 * this is App.java class
 */
public class App {
	/**
	 * this is return method
	 */
    public String getGreeting() {
        return "Hello World!";
    }
    /**
     * this is getting print method
     */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
